default: &default
  adapter: postgresql
  encoding: unicode

  url: <%= Rails.application.credentials.dig Rails.env.to_sym, :database, :url %>
  database: <%= Rails.application.credentials.dig Rails.env.to_sym, :database, :name %>
  username: <%= Rails.application.credentials.dig Rails.env.to_sym, :database, :user %>
  password: <%= Rails.application.credentials.dig Rails.env.to_sym, :database, :password %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
