Kind.find_or_create_by(title: 'script')
Kind.find_or_create_by(title: 'scene')
Kind.find_or_create_by(title: 'plugin')
Kind.find_or_create_by(title: 'tutorial')

Category.find_or_create_by(title: 'other')
Category.find_or_create_by(title: 'animation')
Category.find_or_create_by(title: 'interactive')
Category.find_or_create_by(title: 'texture')
Category.find_or_create_by(title: 'transformation')
Category.find_or_create_by(title: 'utility')
Category.find_or_create_by(title: 'visibility')
